services:

  build32:
    build:
      context: .
      dockerfile: Dockerfile32
    privileged: true
    volumes:
      - "./:/home/jenkins/out"

  build64:
    build:
      context: .
      dockerfile: Dockerfile64
    privileged: true
    volumes:
      - "./:/home/jenkins/out"
